"use client";
import { useEffect, useMemo, useState } from "react";

type Msg={id:number;role:"user"|"bot";text:string;topic?:string};
type EventItem={id:number;title:string;date:string;done:boolean;tag:string};
const answers:Record<string,{title:string;summary:string;steps:string[];meta:string[],source:string}>={
 card:{title:"学生证补办指南",summary:"先联系学院教务办公室确认本学期受理方式，再准备材料办理。",steps:["准备身份证明、校园卡和近期证件照","向所在学院教务办公室登记并填写申请","按最新通知缴费（如有）并等待制证","收到通知后由本人携有效证件领取"],meta:["预计 3–10 个工作日","材料：3–4 项","建议先电话确认"],source:"学院教务办 / 学校教务处（演示数据，需上线前核验）"},
 medical:{title:"学生医保报销",summary:"票据原件、费用明细和诊疗材料最关键，建议提交前先扫描留档。",steps:["确认就诊医院及费用属于报销范围","整理票据原件、费用明细、诊断证明与病历","携身份证明、校园卡及银行卡信息到经办窗口","记录受理时间，按通知查询审核结果"],meta:["政策时效性强","保留票据原件","先咨询校医院"],source:"校医院医保窗口（演示流程，具体以最新政策为准）"},
 study:{title:"自习场地推荐",summary:"如果需要长时间专注，优先图书馆安静区；讨论任务请选择研讨空间。",steps:["深度学习：图书馆安静阅览区，建议 2–4 小时","小组讨论：预约研讨空间，避免影响安静区域","课间学习：就近查询无课教室，当日确认占用","需要电脑：优先选择有插座、网络稳定的位置"],meta:["安静度 ★★★★★","建议错峰 18:00 前","可继续补充位置"],source:"校园场馆信息库（开放时间以现场公告为准）"},
 food:{title:"高性价比餐食推荐",summary:"按 15 元左右预算，优先选择食堂基础套餐，荤素搭配更稳定。",steps:["¥10–15：基础套餐、面食或盖饭窗口","¥15–22：一荤两素，适合晚自习前补充能量","赶时间：选择离下一节课教学楼最近的食堂","告诉我位置、预算和忌口，可进一步筛选"],meta:["人均 ¥12–18","取餐约 8–15 分钟","支持忌口筛选"],source:"学生反馈样本（价格和窗口需定期更新）"},
 express:{title:"快递取件助手",summary:"先看短信中的驿站名称和取件码，再根据宿舍区选择最近路线。",steps:["确认快递公司、驿站名称与取件码","避开午间和晚课后高峰时段","大件快递提前准备手推车或联系代取","补充你的宿舍区，我可以缩小路线范围"],meta:["建议错峰取件","大件提前确认","支持宿舍区筛选"],source:"校园生活设施库（正式版接入校内坐标）"},
 deadline:{title:"近期关键节点",summary:"选课、四六级和体测最容易错过，建议提前 3 天和 1 天各提醒一次。",steps:["选课：核对培养方案、课程容量和冲突","四六级：提前准备证件照并核对学籍信息","体测：确认分组和场地，考前避免突击训练","缓考/奖助学金：以学院通知截止时间为准"],meta:["3 类重点提醒","建议双重提醒","日期为演示数据"],source:"教务与学院通知（页面日期仅用于演示）"},
 arrival:{title:"新生入校清单",summary:"完成身份、住宿、网络、课表和应急信息五类事项，就能快速进入校园节奏。",steps:["完成学院报到与身份核验","领取校园卡并检查基本信息","办理宿舍入住、熟悉消防通道","连接校园网络并登录教务系统","确认课表、教学楼和第一周安排","收藏校医院、保卫处等应急联系方式"],meta:["共 6 项","约 1 天完成","建议按顺序办理"],source:"新生报到通用清单（正式版按当年通知更新）"},
 default:{title:"我还需要一点信息",summary:"我能处理校园地点、办事流程、日程提醒和生活推荐。你可以说得更具体一点。",steps:["问地点：例如“离 21B 最近的安静自习室”","问办事：例如“缓考申请需要什么材料”","做计划：例如“帮我安排今晚 2 小时复习”","找吃的：例如“15 元以内、不吃辣、离教学楼近”"],meta:["支持口语提问","会主动追问","答案标注来源"],source:"衡园小鲸能力说明"}
};
function topicOf(q:string){if(/学生证|证件|补办/.test(q))return"card";if(/医保|报销|医院|就医/.test(q))return"medical";if(/自习|图书馆|教室|学习/.test(q))return"study";if(/食堂|吃|餐|预算|饭/.test(q))return"food";if(/快递|驿站|取件/.test(q))return"express";if(/选课|四六级|体测|报名|节点|提醒/.test(q))return"deadline";if(/新生|报到|入校|清单/.test(q))return"arrival";return"default"}
const quick=["学生证丢了怎么补办？","今晚哪里适合安静自习？","15 元左右吃什么？","最近有哪些报名节点？"];
export default function Home(){
 const [view,setView]=useState("chat"),[input,setInput]=useState(""),[messages,setMessages]=useState<Msg[]>([{id:1,role:"bot",text:"你好，我是衡园小鲸 🐋\n我能帮你查校园资源、理清办事流程、规划日程。今天想先解决什么？"}]);
 const [active,setActive]=useState("arrival"),[saved,setSaved]=useState<string[]>([]),[events,setEvents]=useState<EventItem[]>([{id:1,title:"新生选课确认",date:"2026-09-18",done:false,tag:"教务"},{id:2,title:"四六级报名",date:"2026-09-25",done:false,tag:"考试"},{id:3,title:"秋季体质健康测试",date:"2026-10-09",done:false,tag:"体测"}]);
 useEffect(()=>{try{const x=localStorage.getItem("heu-agent");if(x){const d=JSON.parse(x);if(d.events)setEvents(d.events);if(d.saved)setSaved(d.saved);if(d.messages)setMessages(d.messages)}}catch{}},[]);
 useEffect(()=>{localStorage.setItem("heu-agent",JSON.stringify({events,saved,messages:messages.slice(-20)}))},[events,saved,messages]);
 const stats=useMemo(()=>({open:events.filter(e=>!e.done).length,done:events.filter(e=>e.done).length}),[events]);
 function send(text=input){const q=text.trim();if(!q)return;const t=topicOf(q),a=answers[t];setMessages(m=>[...m,{id:Date.now(),role:"user",text:q},{id:Date.now()+1,role:"bot",text:a.summary,topic:t}]);setActive(t);setInput("");setView("chat")}
 function addEvent(title:string){if(events.some(e=>e.title===title))return;setEvents(e=>[...e,{id:Date.now(),title,date:new Date(Date.now()+3*864e5).toISOString().slice(0,10),done:false,tag:"自定义"}])}
 function toggleSave(k:string){setSaved(s=>s.includes(k)?s.filter(x=>x!==k):[...s,k])}
 const a=answers[active];
 return <div className="shell">
  <aside className="sidebar"><div className="brand"><div className="whale">鲸</div><div><strong>衡园小鲸</strong><small>HEU CAMPUS AI</small></div></div><nav>
   {[['chat','✦','智能问答'],['services','▦','办事大厅'],['places','⌖','校园探索'],['schedule','◷','我的日程'],['saved','♡','我的收藏']].map(x=><button key={x[0]} className={view===x[0]?"on":""} onClick={()=>setView(x[0])}><i>{x[1]}</i>{x[2]}{x[0]==='schedule'&&stats.open>0?<em>{stats.open}</em>:null}</button>)}
  </nav><div className="side-foot"><span className="live-dot"/>知识库演示版 · 2026.07<small>重要信息请以校方最新通知为准</small></div></aside>
  <main><header><div><b>{view==='chat'?'智能问答':view==='services'?'办事大厅':view==='places'?'校园探索':view==='schedule'?'我的日程':'我的收藏'}</b><span>哈尔滨工程大学新生校园助手</span></div><div className="header-actions"><button title="通知">♢<em>{stats.open}</em></button><div className="avatar">新</div></div></header>
   {view==='chat'&&<div className="workspace"><section className="conversation"><div className="welcome"><span>AI CAMPUS GUIDE</span><h1>你好，新同学<br/><i>今天想了解什么？</i></h1><p>校园生活的大小问题，一句话交给小鲸。</p></div><div className="quick-row">{quick.map(q=><button key={q} onClick={()=>send(q)}>{q}</button>)}</div><div className="messages">{messages.map(m=><div className={'msg '+m.role} key={m.id}>{m.role==='bot'&&<div className="bot-icon">鲸</div>}<div className="bubble">{m.text.split('\n').map((x,i)=><span key={i}>{x}</span>)}{m.topic&&<button className="detail-link" onClick={()=>setActive(m.topic!)}>查看完整方案 →</button>}</div></div>)}</div><div className="composer"><button>＋</button><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="问问小鲸：地点、流程、日程、餐食……"/><button className="send" onClick={()=>send()}>发送 ↗</button></div><p className="privacy">本页面不上传个人数据 · 回答附信息来源 · 重要事项请二次核验</p></section>
    <aside className="context"><div className="context-top"><span className="topic">{a.title}</span><button onClick={()=>toggleSave(active)}>{saved.includes(active)?'♥ 已收藏':'♡ 收藏'}</button></div><h2>{a.summary}</h2><div className="chips">{a.meta.map(x=><span key={x}>{x}</span>)}</div><ol>{a.steps.map((x,i)=><li key={x}><b>{i+1}</b><span>{x}</span></li>)}</ol><div className="context-actions"><button onClick={()=>addEvent(a.title)}>＋ 加入日程</button><button onClick={()=>navigator.clipboard?.writeText(a.title+'\n'+a.steps.join('\n'))}>复制清单</button></div><div className="source"><b>信息来源</b><span>{a.source}</span></div></aside></div>}
   {view==='services'&&<Page title="输入业务名称，材料、地点、流程一次讲清" sub="覆盖证件、医保、学业与社团等高频业务"><div className="card-grid">{['card','medical','deadline','arrival'].map(k=><Feature key={k} k={k} onOpen={()=>{setActive(k);setView('chat')}} saved={saved.includes(k)} onSave={()=>toggleSave(k)}/>)}</div></Page>}
   {view==='places'&&<Page title="从当前位置出发，找到合适的校园空间" sub="按距离、安静度、预算和开放状态筛选"><div className="map-card"><div className="fake-map"><span className="road r1"/><span className="road r2"/><b className="pin p1">图书馆</b><b className="pin p2">美食城</b><b className="pin p3">快递驿站</b><div className="you">你</div></div><div className="place-list">{[['📚','图书馆安静区','安静度 5.0 · 约 6 分钟'],['🍜','学生美食城','人均 ¥12–18 · 约 4 分钟'],['📦','快递综合服务点','取件 · 约 8 分钟']].map(x=><button key={x[1]} onClick={()=>send(x[1])}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span><em>›</em></button>)}</div></div></Page>}
   {view==='schedule'&&<Page title="把重要节点变成看得见的计划" sub={`${stats.open} 项待完成 · ${stats.done} 项已完成`}><div className="schedule-layout"><div className="event-list">{events.map(e=><div className={'event '+(e.done?'done':'')} key={e.id}><button className="check" onClick={()=>setEvents(es=>es.map(x=>x.id===e.id?{...x,done:!x.done}:x))}>{e.done?'✓':''}</button><div><b>{e.title}</b><small>{e.date} · {e.tag}</small></div><button className="remove" onClick={()=>setEvents(es=>es.filter(x=>x.id!==e.id))}>×</button></div>)}</div><AddEvent onAdd={(title,date)=>setEvents(e=>[...e,{id:Date.now(),title,date,done:false,tag:'自定义'}])}/></div></Page>}
   {view==='saved'&&<Page title="收藏的重要流程与校园信息" sub="保存在当前浏览器中，刷新不会丢失"><div className="card-grid">{saved.length?saved.map(k=><Feature key={k} k={k} onOpen={()=>{setActive(k);setView('chat')}} saved onSave={()=>toggleSave(k)}/>):<div className="empty"><b>还没有收藏</b><p>打开任意完整方案，点击“收藏”即可保存。</p></div>}</div></Page>}
  </main></div>
}
function Page({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="page"><div className="page-title"><span>衡园小鲸 · 一站式校园服务</span><h1>{title}</h1><p>{sub}</p></div>{children}</section>}
function Feature({k,onOpen,saved,onSave}:{k:string;onOpen:()=>void;saved:boolean;onSave:()=>void}){const a=answers[k];return <article className="feature"><div className="feature-head"><span>{k==='card'?'🎓':k==='medical'?'✚':k==='deadline'?'◷':'🧭'}</span><button onClick={onSave}>{saved?'♥':'♡'}</button></div><h3>{a.title}</h3><p>{a.summary}</p><div>{a.meta.slice(0,2).map(x=><small key={x}>{x}</small>)}</div><button className="open" onClick={onOpen}>查看完整指南 →</button></article>}
function AddEvent({onAdd}:{onAdd:(t:string,d:string)=>void}){const[t,setT]=useState(""),[d,setD]=useState(new Date().toISOString().slice(0,10));return <div className="add-event"><span>NEW REMINDER</span><h3>添加自定义提醒</h3><label>事项名称<input value={t} onChange={e=>setT(e.target.value)} placeholder="例如：学院材料提交"/></label><label>日期<input type="date" value={d} onChange={e=>setD(e.target.value)}/></label><button onClick={()=>{if(t.trim()){onAdd(t.trim(),d);setT("")}}}>添加到日程</button></div>}
